import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono, Space_Grotesk } from "next/font/google";
import Script from "next/script";
import { TooltipProvider } from "@/components/ui/tooltip";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Display font — used for headings and hero titles
const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const BASE_URL = "https://praxialabs.com";

export const metadata: Metadata = {
  metadataBase: new URL(BASE_URL),
  title: {
    default: "Praxia Labs | Automatizacion con IA para empresas",
    template: "%s | Praxia Labs",
  },
  description:
    "Praxia Labs automatiza los procesos de tu empresa con agentes IA. Facturas, aprobaciones, seguimiento de clientes — en automatico, sin codigo, operativo en menos de 48h.",
  keywords: ["agentes IA", "automatizacion empresarial", "IA para pymes", "automatizacion procesos", "Spain AI studio"],
  authors: [{ name: "Praxia Labs", url: BASE_URL }],
  creator: "Praxia Labs",
  openGraph: {
    type: "website",
    locale: "es_ES",
    url: BASE_URL,
    siteName: "Praxia Labs",
    title: "Praxia Labs | Automatizacion con IA para empresas",
    description:
      "Agentes IA que automatizan los procesos manuales de tu empresa. Sin codigo. Operativo en menos de 48 horas.",
    // OG image is auto-generated by src/app/opengraph-image.tsx (Next.js ImageResponse)
    // No need to specify images here — Next.js picks it up automatically from the route file
  },
  twitter: {
    card: "summary_large_image",
    title: "Praxia Labs | Automatizacion con IA",
    description: "Agentes IA que automatizan los procesos manuales de tu empresa.",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large" },
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es" className={`${geistSans.variable} ${geistMono.variable} ${spaceGrotesk.variable} dark`}>
      <head />
      <body className="praxia-body grain min-h-full flex flex-col">
        <Script
          strategy="afterInteractive"
          src="/gtag/js"
        />
        <Script
          id="google-analytics"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'G-CQ6W47R42W', {
        transport_url: 'https://praxialabs.com',
        first_party_collection: true,
      });
    `,
          }}
        />
        <TooltipProvider>
          <main className="flex-1">
            {children}
          </main>
        </TooltipProvider>
      </body>
    </html>
  );
}